apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: "5s"

  - name: Jaeger
    type: jaeger
    uid: jaeger
    url: http://jaeger:16686

  - name: PostgreSQL
    type: postgres
    uid: postgres
    url: postgres:5432
    database: memehub
    user: memehub
    secureJsonData:
      password: memehub
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    url: http://clickhouse:8123
    jsonData:
      server: clickhouse
      port: 8123
      defaultDatabase: default
      username: default
      tlsSkipVerify: true
